version: "3.6"

services:
  app:
    build: ./
    container_name: thoughts-app
    volumes:
      - ./:/Hades
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - thoughts-network
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=thoughtsDb
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - thoughts-network

networks:
  thoughts-network:
    driver: bridge